In [1]:
import tensorflow as tf
import numpy as np

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
trX = np.linspace(-1, 1, 101)
trY = 2 * trX + np.random.randn(*trX.shape) * 0.33

In [7]:
trX.shape

(101,)

In [4]:
trX

array([-1.  , -0.98, -0.96, -0.94, -0.92, -0.9 , -0.88, -0.86, -0.84,
       -0.82, -0.8 , -0.78, -0.76, -0.74, -0.72, -0.7 , -0.68, -0.66,
       -0.64, -0.62, -0.6 , -0.58, -0.56, -0.54, -0.52, -0.5 , -0.48,
       -0.46, -0.44, -0.42, -0.4 , -0.38, -0.36, -0.34, -0.32, -0.3 ,
       -0.28, -0.26, -0.24, -0.22, -0.2 , -0.18, -0.16, -0.14, -0.12,
       -0.1 , -0.08, -0.06, -0.04, -0.02,  0.  ,  0.02,  0.04,  0.06,
        0.08,  0.1 ,  0.12,  0.14,  0.16,  0.18,  0.2 ,  0.22,  0.24,
        0.26,  0.28,  0.3 ,  0.32,  0.34,  0.36,  0.38,  0.4 ,  0.42,
        0.44,  0.46,  0.48,  0.5 ,  0.52,  0.54,  0.56,  0.58,  0.6 ,
        0.62,  0.64,  0.66,  0.68,  0.7 ,  0.72,  0.74,  0.76,  0.78,
        0.8 ,  0.82,  0.84,  0.86,  0.88,  0.9 ,  0.92,  0.94,  0.96,
        0.98,  1.  ])

Return a sample (or samples) from the "standard normal" distribution.

In [6]:
np.random.randn(*trX.shape)

array([ 0.78666489,  1.27183809, -1.31401533, -0.90090058, -0.39443776,
       -1.97906459, -0.42225051, -1.11141259,  0.29188455, -0.33264542,
       -0.88356207, -0.1709142 ,  2.33323628, -1.40655688, -0.21451025,
       -0.68033237, -1.27680677, -0.09453797, -1.22769221,  0.63451359,
       -0.92027973,  0.29065541, -1.40391703,  0.00661505, -0.91508656,
       -2.17882974,  0.8566536 , -0.82716645,  0.56111492,  1.33048743,
       -2.13736777,  1.39327297,  0.07569045, -0.2175482 ,  0.970467  ,
       -1.42203978,  1.18474815, -1.2613262 ,  0.44507084, -0.43977574,
        0.14299818,  0.01393642, -0.94252566, -0.41074087,  0.4124829 ,
        0.38424982, -0.92594795, -0.65364021, -0.50461888,  0.02631241,
        0.67849111,  0.80091652,  2.0261109 ,  3.25130631,  0.38036905,
       -1.7112683 , -0.1505672 , -0.41138269, -0.30776507,  1.78552393,
        0.32382823,  1.25076208,  0.61267777,  0.33196155,  0.52437312,
        1.0645422 , -1.88835631,  0.28115709, -0.23899954, -0.59

In [5]:
trY

array([-1.67854546, -1.96974287, -2.12592868, -1.90722091, -1.81516117,
       -1.71797281, -1.84528801, -1.91779073, -1.34697159, -1.84546946,
       -1.90782242, -0.98243025, -1.04098336, -1.20505783, -1.61808693,
       -2.04398791, -1.29865154, -1.6848871 , -1.3824192 , -1.34353175,
       -1.26067217, -1.23617116, -1.35160509, -1.15340697, -0.77664244,
       -0.78861238, -0.30054501, -0.75382317, -0.61634216, -0.90825647,
       -1.08028447, -0.59865773, -1.14194918, -0.73468735, -0.93791379,
       -0.47942865, -0.82497599, -0.50749793, -0.35396635, -0.76565927,
        0.02801471, -0.6263143 , -0.50726261, -0.30279115,  0.00295082,
       -0.44503258, -0.44538952, -0.6998675 ,  0.03765781, -0.66598099,
        0.06434976, -0.41231487, -0.11510051,  0.40642681,  0.59329049,
        0.17735813, -0.53297358,  0.56999799,  0.32780374,  0.36777335,
        0.03499989,  0.21160811,  0.35552589,  0.96611111,  0.27183456,
        0.98802099,  0.53734036,  0.37768339,  0.99905292,  0.59

In [8]:
X = tf.placeholder("float")
Y = tf.placeholder("float")

def model(X, w):
    return tf.multiply(X, w)

w = tf.Variable(0.0, name="weights")
y_model = model(X, w)

# Computes square of x element-wise.
cost = tf.square(Y - y_model)

train_op = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
# construct an optimizer to minimize cost and fit line to my data

Lauch the graph in a session

In [9]:
with tf.Session() as sess:
    # you need to initialize variables (in this case just variable W)
    tf.global_variables_initializer().run()
    
    for i in range(100):
        for (x, y) in zip(trX, trY):
            sess.run(train_op, feed_dict = {X:x, Y:y})
    
    print(sess.run(w))

1.9937971


It should be something around 2